## NumPy_2
#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел от 12 до 24 невключительно.

In [1]:
import numpy as np

a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [87]:
det = [i for i in np.arange(12, 0, -1) if len(a) % i ==0]

arrs = [a.reshape(det[i], det[len(det) - i - 1]) for i in np.arange(5)]

for arr in arrs:
    print(f'array{arr.shape}, dim = {arr.ndim}\n{arr}\n')


array(12, 1), dim = 2
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

array(6, 2), dim = 2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

array(4, 3), dim = 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

array(3, 4), dim = 2
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

array(2, 6), dim = 2
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]



#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах — для обозначения числа столбцов, в двух — для строк).

In [88]:
arrs_col = [a.reshape(i, -1) for i in det[:3]]
arrs_row = [a.reshape(-1, i) for i in det[3:-1]]
arrs = arrs_col + arrs_row

for arr in arrs:
    print(f'array{arr.shape}, dim = {arr.ndim}\n{arr}\n')


array(12, 1), dim = 2
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

array(6, 2), dim = 2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

array(4, 3), dim = 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

array(4, 3), dim = 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

array(6, 2), dim = 2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]



#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [93]:
print(f'Размерность для подобного массива Numpy = {a.reshape(12, 1).ndim}, следовательно он не одномерный')

Размерность для подобного массива Numpy = 2, следовательно он не одномерный


#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [104]:
b = np.random.randn(3, 4)
print(f'array{b.shape}, size ={b.size}\n{b}')
print(f'array{b.flatten().shape}, size ={b.flatten().size}\n{b.flatten()}')

array(3, 4), size =12
[[-0.36451971 -0.69221212 -0.87660546 -0.48060348]
 [-0.60247514 -0.09438016 -0.78071697  0.90532541]
 [ 0.78236757  0.52652643  1.59259807  1.44568545]]
array(12,), size =12
[-0.36451971 -0.69221212 -0.87660546 -0.48060348 -0.60247514 -0.09438016
 -0.78071697  0.90532541  0.78236757  0.52652643  1.59259807  1.44568545]


#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [34]:
a = np.arange(20, 0, -2)
b = a.reshape(1, 10)
print(f'Сравнение двух матриц: a = {a} и b = {b}\n'
      f'1. Размерность матриц: a = {a.size}, b = {b.size}. {a.size == b.size}\n'
      f'2. Поэлементное равенство матриц: {a == b}\n'
      f'3. Явлвяются ли матрицы одним объектом: {a is b}\n'
      f'4. Форма матриц, их идентичность: a{a.shape} b{b.shape}. {a.shape == b.shape}\n'
      f'Вывод:\n'
      f'При равенстве размеров и элементов матриц a и b, тем не менее они являются\n'
      f'разными объектами и имеют разную форму')

Сравнение двух матриц: a = [20 18 16 14 12 10  8  6  4  2] и b = [[20 18 16 14 12 10  8  6  4  2]]
1. Размерность матриц: a = 10, b = 10. True
2. Поэлементное равенство матриц: [[ True  True  True  True  True  True  True  True  True  True]]
3. Явлвяются ли матрицы одним объектом: False
4. Форма матриц, их идентичность: a(10,) b(1, 10). False
Вывод:
При равенстве размеров и элементов матриц a и b, тем не менее они являются
разными объектами и имеют разную форму


#### 7. Вертикально соединить массивы a и b. a — двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
#### Итоговый массив v должен иметь атрибут size, равный 10.

In [56]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis=0)
print(f'{v}\nv.size = {v.size}')

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
v.size = 10


In [58]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
v = np.vstack((a, b))
print(f'{v}\nv.size = {v.size}')

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
v.size = 10


#### 8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
#### Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [60]:
a = np.arange(12)
A = a.reshape(4, -1)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [110]:
B = A.dot(At)
print(f'{B}\n\nРазмер матрицы B = {B.shape[0]}\n'
      f'Ранг матрицы B = {np.linalg.matrix_rank(B)}\n'
      f'Ранг матрицы меньше ее размера, следовательно есть линейно зависимые строки\n'
      f'в этом случае определитель должен быть рвен 0, а так же, нет возможности вычислить\n'
      f'обратную матрицу\n'
      f'Проверка утверждения про определитель: det(B) = {np.linalg.det(B)}')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

Размер матрицы B = 4
Ранг матрицы B = 2
Ранг матрицы меньше ее размера, следовательно есть линейно зависимые строки
в этом случае определитель должен быть рвен 0, а так же, нет возможности вычислить
обратную матрицу
Проверка утверждения про определитель: det(B) = 0.0


#### 9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [150]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [159]:
C = c.reshape(int(np.sqrt(c.size)), -1)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [167]:
D = C * 10 + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [168]:
D_inv = np.linalg.inv(D)
print(f'Определитель D = {np.linalg.det(D)}\n'
      f'Ранг D = {np.linalg.matrix_rank(D)}\n'
      f'Обратная матрица D_inv:\n{D_inv}')

Определитель D = -28511999.999999944
Ранг D = 4
Обратная матрица D_inv:
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [169]:
D.dot(D_inv).round()

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0.,  0.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0., -0.,  1.]])

#### 10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные — к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C — в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [170]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [171]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])