## NumPy_2
#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел от 12 до 24 невключительно.

In [1]:
import numpy as np

a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [87]:
det = [i for i in np.arange(12, 0, -1) if len(a) % i ==0]

arrs = [a.reshape(det[i], det[len(det) - i - 1]) for i in np.arange(5)]

for arr in arrs:
    print(f'array{arr.shape}, dim = {arr.ndim}\n{arr}\n')


array(12, 1), dim = 2
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

array(6, 2), dim = 2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

array(4, 3), dim = 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

array(3, 4), dim = 2
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

array(2, 6), dim = 2
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]



#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах — для обозначения числа столбцов, в двух — для строк).

In [88]:
arrs_col = [a.reshape(i, -1) for i in det[:3]]
arrs_row = [a.reshape(-1, i) for i in det[3:-1]]
arrs = arrs_col + arrs_row

for arr in arrs:
    print(f'array{arr.shape}, dim = {arr.ndim}\n{arr}\n')


array(12, 1), dim = 2
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

array(6, 2), dim = 2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

array(4, 3), dim = 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

array(4, 3), dim = 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

array(6, 2), dim = 2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]



#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [93]:
print(f'Размерность для подобного массива Numpy = {a.reshape(12, 1).ndim}, следовательно он не одномерный')

Размерность для подобного массива Numpy = 2, следовательно он не одномерный


#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [104]:
b = np.random.randn(3, 4)
print(f'array{b.shape}, size ={b.size}\n{b}')
print(f'array{b.flatten().shape}, size ={b.flatten().size}\n{b.flatten()}')

array(3, 4), size =12
[[-0.36451971 -0.69221212 -0.87660546 -0.48060348]
 [-0.60247514 -0.09438016 -0.78071697  0.90532541]
 [ 0.78236757  0.52652643  1.59259807  1.44568545]]
array(12,), size =12
[-0.36451971 -0.69221212 -0.87660546 -0.48060348 -0.60247514 -0.09438016
 -0.78071697  0.90532541  0.78236757  0.52652643  1.59259807  1.44568545]


#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [3]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])